name: mindfulness_app
description: "Nidara: mindfulness e higiene del sueño."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  supabase_flutter: ^2.8.1
  provider: ^6.0.0
  flutter_dotenv: ^6.0.0
  just_audio: ^0.10.5
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^4.1.1
  timezone: ^0.11.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  audioplayers: ^6.6.0
  file_picker: ^11.0.2
  path: ^1.9.1
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/sounds/bell.wav
    - assets/img/Icono_Minfulnes.png
    - assets/img/Calma_Icon.png
    - assets/sounds/burbuja.wav
    - assets/sounds/platillo.wav
